// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/state_service/service.proto

package state_iface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_proto_state_service_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_service_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_proto_state_service_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_state_service_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_service_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_state_service_service_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Item) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Item) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type ItemResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stored        bool                   `protobuf:"varint,1,opt,name=stored,proto3" json:"stored,omitempty"`
	Data          *Item                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemResult) Reset() {
	*x = ItemResult{}
	mi := &file_proto_state_service_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemResult) ProtoMessage() {}

func (x *ItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_service_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemResult.ProtoReflect.Descriptor instead.
func (*ItemResult) Descriptor() ([]byte, []int) {
	return file_proto_state_service_service_proto_rawDescGZIP(), []int{2}
}

func (x *ItemResult) GetStored() bool {
	if x != nil {
		return x.Stored
	}
	return false
}

func (x *ItemResult) GetData() *Item {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_state_service_service_proto protoreflect.FileDescriptor

const file_proto_state_service_service_proto_rawDesc = "" +
	"\n" +
	"!proto/state_service/service.proto\x12\vstate_iface\"\x1a\n" +
	"\x06GetReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"@\n" +
	"\x04Item\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\"K\n" +
	"\n" +
	"ItemResult\x12\x16\n" +
	"\x06stored\x18\x01 \x01(\bR\x06stored\x12%\n" +
	"\x04data\x18\x02 \x01(\v2\x11.state_iface.ItemR\x04data2\xa4\x01\n" +
	"\fStateService\x12+\n" +
	"\x03Set\x12\x11.state_iface.Item\x1a\x11.state_iface.Item\x123\n" +
	"\x03Get\x12\x13.state_iface.GetReq\x1a\x17.state_iface.ItemResult\x122\n" +
	"\n" +
	"SetOrStore\x12\x11.state_iface.Item\x1a\x11.state_iface.ItemB\x1bZ\x19./state_iface;state_ifaceb\x06proto3"

var (
	file_proto_state_service_service_proto_rawDescOnce sync.Once
	file_proto_state_service_service_proto_rawDescData []byte
)

func file_proto_state_service_service_proto_rawDescGZIP() []byte {
	file_proto_state_service_service_proto_rawDescOnce.Do(func() {
		file_proto_state_service_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_state_service_service_proto_rawDesc), len(file_proto_state_service_service_proto_rawDesc)))
	})
	return file_proto_state_service_service_proto_rawDescData
}

var file_proto_state_service_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_state_service_service_proto_goTypes = []any{
	(*GetReq)(nil),     // 0: state_iface.GetReq
	(*Item)(nil),       // 1: state_iface.Item
	(*ItemResult)(nil), // 2: state_iface.ItemResult
}
var file_proto_state_service_service_proto_depIdxs = []int32{
	1, // 0: state_iface.ItemResult.data:type_name -> state_iface.Item
	1, // 1: state_iface.StateService.Set:input_type -> state_iface.Item
	0, // 2: state_iface.StateService.Get:input_type -> state_iface.GetReq
	1, // 3: state_iface.StateService.SetOrStore:input_type -> state_iface.Item
	1, // 4: state_iface.StateService.Set:output_type -> state_iface.Item
	2, // 5: state_iface.StateService.Get:output_type -> state_iface.ItemResult
	1, // 6: state_iface.StateService.SetOrStore:output_type -> state_iface.Item
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_state_service_service_proto_init() }
func file_proto_state_service_service_proto_init() {
	if File_proto_state_service_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_state_service_service_proto_rawDesc), len(file_proto_state_service_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_state_service_service_proto_goTypes,
		DependencyIndexes: file_proto_state_service_service_proto_depIdxs,
		MessageInfos:      file_proto_state_service_service_proto_msgTypes,
	}.Build()
	File_proto_state_service_service_proto = out.File
	file_proto_state_service_service_proto_goTypes = nil
	file_proto_state_service_service_proto_depIdxs = nil
}
