// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/infra_service/infra.proto

package infra_iface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        uint64                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_proto_infra_service_infra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infra_service_infra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_proto_infra_service_infra_proto_rawDescGZIP(), []int{0}
}

func (x *VersionRequest) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_proto_infra_service_infra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infra_service_infra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_infra_service_infra_proto_rawDescGZIP(), []int{1}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_infra_service_infra_proto protoreflect.FileDescriptor

const file_proto_infra_service_infra_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/infra_service/infra.proto\x12\vinfra_iface\")\n" +
	"\x0eVersionRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x04R\x06teamId\"+\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion2W\n" +
	"\fInfraService\x12G\n" +
	"\n" +
	"GetVersion\x12\x1b.infra_iface.VersionRequest\x1a\x1c.infra_iface.VersionResponseB\x1bZ\x19./infra_iface;infra_ifaceb\x06proto3"

var (
	file_proto_infra_service_infra_proto_rawDescOnce sync.Once
	file_proto_infra_service_infra_proto_rawDescData []byte
)

func file_proto_infra_service_infra_proto_rawDescGZIP() []byte {
	file_proto_infra_service_infra_proto_rawDescOnce.Do(func() {
		file_proto_infra_service_infra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_infra_service_infra_proto_rawDesc), len(file_proto_infra_service_infra_proto_rawDesc)))
	})
	return file_proto_infra_service_infra_proto_rawDescData
}

var file_proto_infra_service_infra_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_infra_service_infra_proto_goTypes = []any{
	(*VersionRequest)(nil),  // 0: infra_iface.VersionRequest
	(*VersionResponse)(nil), // 1: infra_iface.VersionResponse
}
var file_proto_infra_service_infra_proto_depIdxs = []int32{
	0, // 0: infra_iface.InfraService.GetVersion:input_type -> infra_iface.VersionRequest
	1, // 1: infra_iface.InfraService.GetVersion:output_type -> infra_iface.VersionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_infra_service_infra_proto_init() }
func file_proto_infra_service_infra_proto_init() {
	if File_proto_infra_service_infra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_infra_service_infra_proto_rawDesc), len(file_proto_infra_service_infra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_infra_service_infra_proto_goTypes,
		DependencyIndexes: file_proto_infra_service_infra_proto_depIdxs,
		MessageInfos:      file_proto_infra_service_infra_proto_msgTypes,
	}.Build()
	File_proto_infra_service_infra_proto = out.File
	file_proto_infra_service_infra_proto_goTypes = nil
	file_proto_infra_service_infra_proto_depIdxs = nil
}
