// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/invoice_service/invoice.proto

package invoice_iface

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LimitType int32

const (
	LimitType_UNKNOWN LimitType = 0
	LimitType_DEFAULT LimitType = 1
	LimitType_TEAM    LimitType = 2
)

// Enum value maps for LimitType.
var (
	LimitType_name = map[int32]string{
		0: "UNKNOWN",
		1: "DEFAULT",
		2: "TEAM",
	}
	LimitType_value = map[string]int32{
		"UNKNOWN": 0,
		"DEFAULT": 1,
		"TEAM":    2,
	}
)

func (x LimitType) Enum() *LimitType {
	p := new(LimitType)
	*p = x
	return p
}

func (x LimitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LimitType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_invoice_service_invoice_proto_enumTypes[0].Descriptor()
}

func (LimitType) Type() protoreflect.EnumType {
	return &file_proto_invoice_service_invoice_proto_enumTypes[0]
}

func (x LimitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LimitType.Descriptor instead.
func (LimitType) EnumDescriptor() ([]byte, []int) {
	return file_proto_invoice_service_invoice_proto_rawDescGZIP(), []int{0}
}

type SetLimitInvoiceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ForTeamId     *int64                 `protobuf:"varint,2,opt,name=for_team_id,json=forTeamId,proto3,oneof" json:"for_team_id,omitempty"`
	Threshold     float64                `protobuf:"fixed64,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLimitInvoiceReq) Reset() {
	*x = SetLimitInvoiceReq{}
	mi := &file_proto_invoice_service_invoice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLimitInvoiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLimitInvoiceReq) ProtoMessage() {}

func (x *SetLimitInvoiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invoice_service_invoice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLimitInvoiceReq.ProtoReflect.Descriptor instead.
func (*SetLimitInvoiceReq) Descriptor() ([]byte, []int) {
	return file_proto_invoice_service_invoice_proto_rawDescGZIP(), []int{0}
}

func (x *SetLimitInvoiceReq) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *SetLimitInvoiceReq) GetForTeamId() int64 {
	if x != nil && x.ForTeamId != nil {
		return *x.ForTeamId
	}
	return 0
}

func (x *SetLimitInvoiceReq) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type SetLimitInvoiceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLimitInvoiceRes) Reset() {
	*x = SetLimitInvoiceRes{}
	mi := &file_proto_invoice_service_invoice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLimitInvoiceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLimitInvoiceRes) ProtoMessage() {}

func (x *SetLimitInvoiceRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invoice_service_invoice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLimitInvoiceRes.ProtoReflect.Descriptor instead.
func (*SetLimitInvoiceRes) Descriptor() ([]byte, []int) {
	return file_proto_invoice_service_invoice_proto_rawDescGZIP(), []int{1}
}

func (x *SetLimitInvoiceRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TeamLimitInvoiceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToTeamId      int64                  `protobuf:"varint,1,opt,name=to_team_id,json=toTeamId,proto3" json:"to_team_id,omitempty"`
	FromTeamId    int64                  `protobuf:"varint,2,opt,name=from_team_id,json=fromTeamId,proto3" json:"from_team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamLimitInvoiceReq) Reset() {
	*x = TeamLimitInvoiceReq{}
	mi := &file_proto_invoice_service_invoice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamLimitInvoiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamLimitInvoiceReq) ProtoMessage() {}

func (x *TeamLimitInvoiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invoice_service_invoice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamLimitInvoiceReq.ProtoReflect.Descriptor instead.
func (*TeamLimitInvoiceReq) Descriptor() ([]byte, []int) {
	return file_proto_invoice_service_invoice_proto_rawDescGZIP(), []int{2}
}

func (x *TeamLimitInvoiceReq) GetToTeamId() int64 {
	if x != nil {
		return x.ToTeamId
	}
	return 0
}

func (x *TeamLimitInvoiceReq) GetFromTeamId() int64 {
	if x != nil {
		return x.FromTeamId
	}
	return 0
}

type TeamLimitInvoiceRes struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TeamId                int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ForTeamId             int64                  `protobuf:"varint,2,opt,name=for_team_id,json=forTeamId,proto3" json:"for_team_id,omitempty"`
	LimitType             LimitType              `protobuf:"varint,3,opt,name=limit_type,json=limitType,proto3,enum=invoice_iface.LimitType" json:"limit_type,omitempty"`
	CanCreateOrder        bool                   `protobuf:"varint,4,opt,name=can_create_order,json=canCreateOrder,proto3" json:"can_create_order,omitempty"`
	LimitThressholdAmount float64                `protobuf:"fixed64,5,opt,name=limit_thresshold_amount,json=limitThressholdAmount,proto3" json:"limit_thresshold_amount,omitempty"`
	UnpaidInvoiceAmount   float64                `protobuf:"fixed64,6,opt,name=unpaid_invoice_amount,json=unpaidInvoiceAmount,proto3" json:"unpaid_invoice_amount,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TeamLimitInvoiceRes) Reset() {
	*x = TeamLimitInvoiceRes{}
	mi := &file_proto_invoice_service_invoice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamLimitInvoiceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamLimitInvoiceRes) ProtoMessage() {}

func (x *TeamLimitInvoiceRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invoice_service_invoice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamLimitInvoiceRes.ProtoReflect.Descriptor instead.
func (*TeamLimitInvoiceRes) Descriptor() ([]byte, []int) {
	return file_proto_invoice_service_invoice_proto_rawDescGZIP(), []int{3}
}

func (x *TeamLimitInvoiceRes) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *TeamLimitInvoiceRes) GetForTeamId() int64 {
	if x != nil {
		return x.ForTeamId
	}
	return 0
}

func (x *TeamLimitInvoiceRes) GetLimitType() LimitType {
	if x != nil {
		return x.LimitType
	}
	return LimitType_UNKNOWN
}

func (x *TeamLimitInvoiceRes) GetCanCreateOrder() bool {
	if x != nil {
		return x.CanCreateOrder
	}
	return false
}

func (x *TeamLimitInvoiceRes) GetLimitThressholdAmount() float64 {
	if x != nil {
		return x.LimitThressholdAmount
	}
	return 0
}

func (x *TeamLimitInvoiceRes) GetUnpaidInvoiceAmount() float64 {
	if x != nil {
		return x.UnpaidInvoiceAmount
	}
	return 0
}

type ConfigItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LimitType     LimitType              `protobuf:"varint,2,opt,name=limit_type,json=limitType,proto3,enum=invoice_iface.LimitType" json:"limit_type,omitempty"`
	TeamId        int64                  `protobuf:"varint,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ForTeamId     int64                  `protobuf:"varint,4,opt,name=for_team_id,json=forTeamId,proto3" json:"for_team_id,omitempty"`
	Threshold     float64                `protobuf:"fixed64,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TeamName      string                 `protobuf:"bytes,6,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItem) Reset() {
	*x = ConfigItem{}
	mi := &file_proto_invoice_service_invoice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItem) ProtoMessage() {}

func (x *ConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invoice_service_invoice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItem.ProtoReflect.Descriptor instead.
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return file_proto_invoice_service_invoice_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConfigItem) GetLimitType() LimitType {
	if x != nil {
		return x.LimitType
	}
	return LimitType_UNKNOWN
}

func (x *ConfigItem) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *ConfigItem) GetForTeamId() int64 {
	if x != nil {
		return x.ForTeamId
	}
	return 0
}

func (x *ConfigItem) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *ConfigItem) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

type ConfigListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigListReq) Reset() {
	*x = ConfigListReq{}
	mi := &file_proto_invoice_service_invoice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigListReq) ProtoMessage() {}

func (x *ConfigListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invoice_service_invoice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigListReq.ProtoReflect.Descriptor instead.
func (*ConfigListReq) Descriptor() ([]byte, []int) {
	return file_proto_invoice_service_invoice_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigListReq) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type ConfigListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ConfigItem          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigListRes) Reset() {
	*x = ConfigListRes{}
	mi := &file_proto_invoice_service_invoice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigListRes) ProtoMessage() {}

func (x *ConfigListRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invoice_service_invoice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigListRes.ProtoReflect.Descriptor instead.
func (*ConfigListRes) Descriptor() ([]byte, []int) {
	return file_proto_invoice_service_invoice_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigListRes) GetData() []*ConfigItem {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_invoice_service_invoice_proto protoreflect.FileDescriptor

const file_proto_invoice_service_invoice_proto_rawDesc = "" +
	"\n" +
	"#proto/invoice_service/invoice.proto\x12\rinvoice_iface\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x80\x01\n" +
	"\x12SetLimitInvoiceReq\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12#\n" +
	"\vfor_team_id\x18\x02 \x01(\x03H\x00R\tforTeamId\x88\x01\x01\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x01R\tthresholdB\x0e\n" +
	"\f_for_team_id\".\n" +
	"\x12SetLimitInvoiceRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"U\n" +
	"\x13TeamLimitInvoiceReq\x12\x1c\n" +
	"\n" +
	"to_team_id\x18\x01 \x01(\x03R\btoTeamId\x12 \n" +
	"\ffrom_team_id\x18\x02 \x01(\x03R\n" +
	"fromTeamId\"\x9d\x02\n" +
	"\x13TeamLimitInvoiceRes\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x1e\n" +
	"\vfor_team_id\x18\x02 \x01(\x03R\tforTeamId\x127\n" +
	"\n" +
	"limit_type\x18\x03 \x01(\x0e2\x18.invoice_iface.LimitTypeR\tlimitType\x12(\n" +
	"\x10can_create_order\x18\x04 \x01(\bR\x0ecanCreateOrder\x126\n" +
	"\x17limit_thresshold_amount\x18\x05 \x01(\x01R\x15limitThressholdAmount\x122\n" +
	"\x15unpaid_invoice_amount\x18\x06 \x01(\x01R\x13unpaidInvoiceAmount\"\xc9\x01\n" +
	"\n" +
	"ConfigItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x127\n" +
	"\n" +
	"limit_type\x18\x02 \x01(\x0e2\x18.invoice_iface.LimitTypeR\tlimitType\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\x03R\x06teamId\x12\x1e\n" +
	"\vfor_team_id\x18\x04 \x01(\x03R\tforTeamId\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x01R\tthreshold\x12\x1b\n" +
	"\tteam_name\x18\x06 \x01(\tR\bteamName\"(\n" +
	"\rConfigListReq\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\">\n" +
	"\rConfigListRes\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.invoice_iface.ConfigItemR\x04data*/\n" +
	"\tLimitType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aDEFAULT\x10\x01\x12\b\n" +
	"\x04TEAM\x10\x022\xfb\x02\n" +
	"\x0eInvoiceService\x12{\n" +
	"\x0fGetLimitInvoice\x12\".invoice_iface.TeamLimitInvoiceReq\x1a\".invoice_iface.TeamLimitInvoiceRes\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/get_limit_invoice\x12y\n" +
	"\x0fSetLimitInvoice\x12!.invoice_iface.SetLimitInvoiceReq\x1a!.invoice_iface.SetLimitInvoiceRes\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/set_limit_invoice\x12q\n" +
	"\x10LimitInvoiceList\x12\x1c.invoice_iface.ConfigListReq\x1a\x1c.invoice_iface.ConfigListRes\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/limit_invoice_listB7\x92A\x15\x12\x13\n" +
	"\fUser Service2\x031.0Z\x1d./invoice_iface;invoice_ifaceb\x06proto3"

var (
	file_proto_invoice_service_invoice_proto_rawDescOnce sync.Once
	file_proto_invoice_service_invoice_proto_rawDescData []byte
)

func file_proto_invoice_service_invoice_proto_rawDescGZIP() []byte {
	file_proto_invoice_service_invoice_proto_rawDescOnce.Do(func() {
		file_proto_invoice_service_invoice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_invoice_service_invoice_proto_rawDesc), len(file_proto_invoice_service_invoice_proto_rawDesc)))
	})
	return file_proto_invoice_service_invoice_proto_rawDescData
}

var file_proto_invoice_service_invoice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_invoice_service_invoice_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_invoice_service_invoice_proto_goTypes = []any{
	(LimitType)(0),              // 0: invoice_iface.LimitType
	(*SetLimitInvoiceReq)(nil),  // 1: invoice_iface.SetLimitInvoiceReq
	(*SetLimitInvoiceRes)(nil),  // 2: invoice_iface.SetLimitInvoiceRes
	(*TeamLimitInvoiceReq)(nil), // 3: invoice_iface.TeamLimitInvoiceReq
	(*TeamLimitInvoiceRes)(nil), // 4: invoice_iface.TeamLimitInvoiceRes
	(*ConfigItem)(nil),          // 5: invoice_iface.ConfigItem
	(*ConfigListReq)(nil),       // 6: invoice_iface.ConfigListReq
	(*ConfigListRes)(nil),       // 7: invoice_iface.ConfigListRes
}
var file_proto_invoice_service_invoice_proto_depIdxs = []int32{
	0, // 0: invoice_iface.TeamLimitInvoiceRes.limit_type:type_name -> invoice_iface.LimitType
	0, // 1: invoice_iface.ConfigItem.limit_type:type_name -> invoice_iface.LimitType
	5, // 2: invoice_iface.ConfigListRes.data:type_name -> invoice_iface.ConfigItem
	3, // 3: invoice_iface.InvoiceService.GetLimitInvoice:input_type -> invoice_iface.TeamLimitInvoiceReq
	1, // 4: invoice_iface.InvoiceService.SetLimitInvoice:input_type -> invoice_iface.SetLimitInvoiceReq
	6, // 5: invoice_iface.InvoiceService.LimitInvoiceList:input_type -> invoice_iface.ConfigListReq
	4, // 6: invoice_iface.InvoiceService.GetLimitInvoice:output_type -> invoice_iface.TeamLimitInvoiceRes
	2, // 7: invoice_iface.InvoiceService.SetLimitInvoice:output_type -> invoice_iface.SetLimitInvoiceRes
	7, // 8: invoice_iface.InvoiceService.LimitInvoiceList:output_type -> invoice_iface.ConfigListRes
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_invoice_service_invoice_proto_init() }
func file_proto_invoice_service_invoice_proto_init() {
	if File_proto_invoice_service_invoice_proto != nil {
		return
	}
	file_proto_invoice_service_invoice_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_invoice_service_invoice_proto_rawDesc), len(file_proto_invoice_service_invoice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_invoice_service_invoice_proto_goTypes,
		DependencyIndexes: file_proto_invoice_service_invoice_proto_depIdxs,
		EnumInfos:         file_proto_invoice_service_invoice_proto_enumTypes,
		MessageInfos:      file_proto_invoice_service_invoice_proto_msgTypes,
	}.Build()
	File_proto_invoice_service_invoice_proto = out.File
	file_proto_invoice_service_invoice_proto_goTypes = nil
	file_proto_invoice_service_invoice_proto_depIdxs = nil
}
