package custom_connect

import (
	"context"
	"log"
	"os"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.20.0"

	// Or the latest semantic conventions version
	traceExporter "github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace"
)

func InitTracer(serviceName string) (func(context.Context) error, error) {
	// ctx := context.Background()

	exporter, err := traceExporter.New(
		traceExporter.WithProjectID(os.Getenv("GOOGLE_CLOUD_PROJECT")),
	)
	if err != nil {
		log.Fatalf("failed to create trace exporter: %v", err)
	}

	// Configure the TracerProvider.
	// - WithBatcher: Enables batching of spans, which is more efficient for sending.
	// - WithResource: Adds service-level attributes to all spans generated by this provider.
	tp := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exporter),
		sdktrace.WithResource(resource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.ServiceName(serviceName), // Replace with your service name
		)),
		// Optional: You can add a Sampler here if you don't want to trace all requests.
		// sdktrace.WithSampler(sdktrace.TraceIDRatioBased(0.5)), // Sample 50% of traces
	)

	// Register the TracerProvider globally. This allows you to get a Tracer
	// using `otel.Tracer()` anywhere in your application.
	otel.SetTracerProvider(tp)

	otel.SetTextMapPropagator(
		propagation.NewCompositeTextMapPropagator(
			propagation.TraceContext{}, // uses W3C traceparent header
			propagation.Baggage{},
		),
	)

	return tp.Shutdown, nil
}
