// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: proto/withdrawal_service/withdrawal.proto

package withdrawal_iface

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WithdrawalService_SubmitWithdrawal_FullMethodName = "/withdrawal_iface.WithdrawalService/SubmitWithdrawal"
)

// WithdrawalServiceClient is the client API for WithdrawalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WithdrawalServiceClient interface {
	SubmitWithdrawal(ctx context.Context, in *SubmitWdRequest, opts ...grpc.CallOption) (*CommonResponse, error)
}

type withdrawalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWithdrawalServiceClient(cc grpc.ClientConnInterface) WithdrawalServiceClient {
	return &withdrawalServiceClient{cc}
}

func (c *withdrawalServiceClient) SubmitWithdrawal(ctx context.Context, in *SubmitWdRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, WithdrawalService_SubmitWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WithdrawalServiceServer is the server API for WithdrawalService service.
// All implementations must embed UnimplementedWithdrawalServiceServer
// for forward compatibility.
type WithdrawalServiceServer interface {
	SubmitWithdrawal(context.Context, *SubmitWdRequest) (*CommonResponse, error)
	mustEmbedUnimplementedWithdrawalServiceServer()
}

// UnimplementedWithdrawalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWithdrawalServiceServer struct{}

func (UnimplementedWithdrawalServiceServer) SubmitWithdrawal(context.Context, *SubmitWdRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitWithdrawal not implemented")
}
func (UnimplementedWithdrawalServiceServer) mustEmbedUnimplementedWithdrawalServiceServer() {}
func (UnimplementedWithdrawalServiceServer) testEmbeddedByValue()                           {}

// UnsafeWithdrawalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WithdrawalServiceServer will
// result in compilation errors.
type UnsafeWithdrawalServiceServer interface {
	mustEmbedUnimplementedWithdrawalServiceServer()
}

func RegisterWithdrawalServiceServer(s grpc.ServiceRegistrar, srv WithdrawalServiceServer) {
	// If the following call pancis, it indicates UnimplementedWithdrawalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WithdrawalService_ServiceDesc, srv)
}

func _WithdrawalService_SubmitWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitWdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WithdrawalServiceServer).SubmitWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WithdrawalService_SubmitWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WithdrawalServiceServer).SubmitWithdrawal(ctx, req.(*SubmitWdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WithdrawalService_ServiceDesc is the grpc.ServiceDesc for WithdrawalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WithdrawalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "withdrawal_iface.WithdrawalService",
	HandlerType: (*WithdrawalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitWithdrawal",
			Handler:    _WithdrawalService_SubmitWithdrawal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/withdrawal_service/withdrawal.proto",
}
