// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/withdrawal_service/withdrawal.proto

package withdrawal_iface

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_UNKNOWN TaskStatus = 0
	TaskStatus_TASK_ERROR   TaskStatus = 1
	TaskStatus_TASK_WAITING TaskStatus = 2
	TaskStatus_TASK_PROCESS TaskStatus = 3
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_UNKNOWN",
		1: "TASK_ERROR",
		2: "TASK_WAITING",
		3: "TASK_PROCESS",
	}
	TaskStatus_value = map[string]int32{
		"TASK_UNKNOWN": 0,
		"TASK_ERROR":   1,
		"TASK_WAITING": 2,
		"TASK_PROCESS": 3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_withdrawal_service_withdrawal_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_withdrawal_service_withdrawal_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_withdrawal_service_withdrawal_proto_rawDescGZIP(), []int{0}
}

type ImporterSource int32

const (
	ImporterSource_SOURCE_UNKNOWN ImporterSource = 0
	ImporterSource_SOURCE_CSV     ImporterSource = 1
	ImporterSource_SOURCE_XLS     ImporterSource = 2
	ImporterSource_SOURCE_JSON    ImporterSource = 3
)

// Enum value maps for ImporterSource.
var (
	ImporterSource_name = map[int32]string{
		0: "SOURCE_UNKNOWN",
		1: "SOURCE_CSV",
		2: "SOURCE_XLS",
		3: "SOURCE_JSON",
	}
	ImporterSource_value = map[string]int32{
		"SOURCE_UNKNOWN": 0,
		"SOURCE_CSV":     1,
		"SOURCE_XLS":     2,
		"SOURCE_JSON":    3,
	}
)

func (x ImporterSource) Enum() *ImporterSource {
	p := new(ImporterSource)
	*p = x
	return p
}

func (x ImporterSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImporterSource) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_withdrawal_service_withdrawal_proto_enumTypes[1].Descriptor()
}

func (ImporterSource) Type() protoreflect.EnumType {
	return &file_proto_withdrawal_service_withdrawal_proto_enumTypes[1]
}

func (x ImporterSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImporterSource.Descriptor instead.
func (ImporterSource) EnumDescriptor() ([]byte, []int) {
	return file_proto_withdrawal_service_withdrawal_proto_rawDescGZIP(), []int{1}
}

type OrderMpType int32

const (
	OrderMpType_Custom    OrderMpType = 0
	OrderMpType_Tokopedia OrderMpType = 1
	OrderMpType_Shopee    OrderMpType = 2
	OrderMpType_Tiktok    OrderMpType = 3
	OrderMpType_Lazada    OrderMpType = 4
	OrderMpType_Mengantar OrderMpType = 5
)

// Enum value maps for OrderMpType.
var (
	OrderMpType_name = map[int32]string{
		0: "Custom",
		1: "Tokopedia",
		2: "Shopee",
		3: "Tiktok",
		4: "Lazada",
		5: "Mengantar",
	}
	OrderMpType_value = map[string]int32{
		"Custom":    0,
		"Tokopedia": 1,
		"Shopee":    2,
		"Tiktok":    3,
		"Lazada":    4,
		"Mengantar": 5,
	}
)

func (x OrderMpType) Enum() *OrderMpType {
	p := new(OrderMpType)
	*p = x
	return p
}

func (x OrderMpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderMpType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_withdrawal_service_withdrawal_proto_enumTypes[2].Descriptor()
}

func (OrderMpType) Type() protoreflect.EnumType {
	return &file_proto_withdrawal_service_withdrawal_proto_enumTypes[2]
}

func (x OrderMpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderMpType.Descriptor instead.
func (OrderMpType) EnumDescriptor() ([]byte, []int) {
	return file_proto_withdrawal_service_withdrawal_proto_rawDescGZIP(), []int{2}
}

type TaskListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        uint64                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=withdrawal_iface.TaskStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskListRequest) Reset() {
	*x = TaskListRequest{}
	mi := &file_proto_withdrawal_service_withdrawal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskListRequest) ProtoMessage() {}

func (x *TaskListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_withdrawal_service_withdrawal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskListRequest.ProtoReflect.Descriptor instead.
func (*TaskListRequest) Descriptor() ([]byte, []int) {
	return file_proto_withdrawal_service_withdrawal_proto_rawDescGZIP(), []int{0}
}

func (x *TaskListRequest) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *TaskListRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_UNKNOWN
}

type TaskListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TaskItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskListResponse) Reset() {
	*x = TaskListResponse{}
	mi := &file_proto_withdrawal_service_withdrawal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskListResponse) ProtoMessage() {}

func (x *TaskListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_withdrawal_service_withdrawal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskListResponse.ProtoReflect.Descriptor instead.
func (*TaskListResponse) Descriptor() ([]byte, []int) {
	return file_proto_withdrawal_service_withdrawal_proto_rawDescGZIP(), []int{1}
}

func (x *TaskListResponse) GetItems() []*TaskItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type TaskItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        uint64                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	MpId          uint64                 `protobuf:"varint,2,opt,name=mp_id,json=mpId,proto3" json:"mp_id,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Source        ImporterSource         `protobuf:"varint,5,opt,name=source,proto3,enum=withdrawal_iface.ImporterSource" json:"source,omitempty"`
	MpType        OrderMpType            `protobuf:"varint,6,opt,name=mp_type,json=mpType,proto3,enum=withdrawal_iface.OrderMpType" json:"mp_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskItem) Reset() {
	*x = TaskItem{}
	mi := &file_proto_withdrawal_service_withdrawal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskItem) ProtoMessage() {}

func (x *TaskItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_withdrawal_service_withdrawal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskItem.ProtoReflect.Descriptor instead.
func (*TaskItem) Descriptor() ([]byte, []int) {
	return file_proto_withdrawal_service_withdrawal_proto_rawDescGZIP(), []int{2}
}

func (x *TaskItem) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *TaskItem) GetMpId() uint64 {
	if x != nil {
		return x.MpId
	}
	return 0
}

func (x *TaskItem) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *TaskItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskItem) GetSource() ImporterSource {
	if x != nil {
		return x.Source
	}
	return ImporterSource_SOURCE_UNKNOWN
}

func (x *TaskItem) GetMpType() OrderMpType {
	if x != nil {
		return x.MpType
	}
	return OrderMpType_Custom
}

type SubmitWdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        uint64                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	MpId          uint64                 `protobuf:"varint,2,opt,name=mp_id,json=mpId,proto3" json:"mp_id,omitempty"`
	Source        ImporterSource         `protobuf:"varint,3,opt,name=source,proto3,enum=withdrawal_iface.ImporterSource" json:"source,omitempty"`
	MpType        OrderMpType            `protobuf:"varint,4,opt,name=mp_type,json=mpType,proto3,enum=withdrawal_iface.OrderMpType" json:"mp_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWdRequest) Reset() {
	*x = SubmitWdRequest{}
	mi := &file_proto_withdrawal_service_withdrawal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWdRequest) ProtoMessage() {}

func (x *SubmitWdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_withdrawal_service_withdrawal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWdRequest.ProtoReflect.Descriptor instead.
func (*SubmitWdRequest) Descriptor() ([]byte, []int) {
	return file_proto_withdrawal_service_withdrawal_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitWdRequest) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *SubmitWdRequest) GetMpId() uint64 {
	if x != nil {
		return x.MpId
	}
	return 0
}

func (x *SubmitWdRequest) GetSource() ImporterSource {
	if x != nil {
		return x.Source
	}
	return ImporterSource_SOURCE_UNKNOWN
}

func (x *SubmitWdRequest) GetMpType() OrderMpType {
	if x != nil {
		return x.MpType
	}
	return OrderMpType_Custom
}

func (x *SubmitWdRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_proto_withdrawal_service_withdrawal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_withdrawal_service_withdrawal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_proto_withdrawal_service_withdrawal_proto_rawDescGZIP(), []int{4}
}

func (x *EmptyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_proto_withdrawal_service_withdrawal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_withdrawal_service_withdrawal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_proto_withdrawal_service_withdrawal_proto_rawDescGZIP(), []int{5}
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_withdrawal_service_withdrawal_proto protoreflect.FileDescriptor

const file_proto_withdrawal_service_withdrawal_proto_rawDesc = "" +
	"\n" +
	")proto/withdrawal_service/withdrawal.proto\x12\x10withdrawal_iface\x1a\x1cgoogle/api/annotations.proto\"`\n" +
	"\x0fTaskListRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x04R\x06teamId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.withdrawal_iface.TaskStatusR\x06status\"D\n" +
	"\x10TaskListResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.withdrawal_iface.TaskItemR\x05items\"\xde\x01\n" +
	"\bTaskItem\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x04R\x06teamId\x12\x13\n" +
	"\x05mp_id\x18\x02 \x01(\x04R\x04mpId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x128\n" +
	"\x06source\x18\x05 \x01(\x0e2 .withdrawal_iface.ImporterSourceR\x06source\x126\n" +
	"\amp_type\x18\x06 \x01(\x0e2\x1d.withdrawal_iface.OrderMpTypeR\x06mpType\"\xcb\x01\n" +
	"\x0fSubmitWdRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x04R\x06teamId\x12\x13\n" +
	"\x05mp_id\x18\x02 \x01(\x04R\x04mpId\x128\n" +
	"\x06source\x18\x03 \x01(\x0e2 .withdrawal_iface.ImporterSourceR\x06source\x126\n" +
	"\amp_type\x18\x04 \x01(\x0e2\x1d.withdrawal_iface.OrderMpTypeR\x06mpType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\"\x1e\n" +
	"\fEmptyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x0eCommonResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*R\n" +
	"\n" +
	"TaskStatus\x12\x10\n" +
	"\fTASK_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"TASK_ERROR\x10\x01\x12\x10\n" +
	"\fTASK_WAITING\x10\x02\x12\x10\n" +
	"\fTASK_PROCESS\x10\x03*U\n" +
	"\x0eImporterSource\x12\x12\n" +
	"\x0eSOURCE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"SOURCE_CSV\x10\x01\x12\x0e\n" +
	"\n" +
	"SOURCE_XLS\x10\x02\x12\x0f\n" +
	"\vSOURCE_JSON\x10\x03*[\n" +
	"\vOrderMpType\x12\n" +
	"\n" +
	"\x06Custom\x10\x00\x12\r\n" +
	"\tTokopedia\x10\x01\x12\n" +
	"\n" +
	"\x06Shopee\x10\x02\x12\n" +
	"\n" +
	"\x06Tiktok\x10\x03\x12\n" +
	"\n" +
	"\x06Lazada\x10\x04\x12\r\n" +
	"\tMengantar\x10\x052\xc7\x04\n" +
	"\x11WithdrawalService\x12~\n" +
	"\x10SubmitWithdrawal\x12!.withdrawal_iface.SubmitWdRequest\x1a .withdrawal_iface.CommonResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v4/withdrawal/task/submit\x12v\n" +
	"\vGetTaskList\x12!.withdrawal_iface.TaskListRequest\x1a\".withdrawal_iface.TaskListResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v4/withdrawal/task/list\x12c\n" +
	"\x03Run\x12\x1e.withdrawal_iface.EmptyRequest\x1a .withdrawal_iface.CommonResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v4/withdrawal/run\x12e\n" +
	"\x04Stop\x12\x1e.withdrawal_iface.EmptyRequest\x1a .withdrawal_iface.CommonResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v4/withdrawal/stop\x12n\n" +
	"\vHealthCheck\x12\x1e.withdrawal_iface.EmptyRequest\x1a .withdrawal_iface.CommonResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v4/withdrawal/healthB%Z#./withdrawal_iface;withdrawal_ifaceb\x06proto3"

var (
	file_proto_withdrawal_service_withdrawal_proto_rawDescOnce sync.Once
	file_proto_withdrawal_service_withdrawal_proto_rawDescData []byte
)

func file_proto_withdrawal_service_withdrawal_proto_rawDescGZIP() []byte {
	file_proto_withdrawal_service_withdrawal_proto_rawDescOnce.Do(func() {
		file_proto_withdrawal_service_withdrawal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_withdrawal_service_withdrawal_proto_rawDesc), len(file_proto_withdrawal_service_withdrawal_proto_rawDesc)))
	})
	return file_proto_withdrawal_service_withdrawal_proto_rawDescData
}

var file_proto_withdrawal_service_withdrawal_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_withdrawal_service_withdrawal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_withdrawal_service_withdrawal_proto_goTypes = []any{
	(TaskStatus)(0),          // 0: withdrawal_iface.TaskStatus
	(ImporterSource)(0),      // 1: withdrawal_iface.ImporterSource
	(OrderMpType)(0),         // 2: withdrawal_iface.OrderMpType
	(*TaskListRequest)(nil),  // 3: withdrawal_iface.TaskListRequest
	(*TaskListResponse)(nil), // 4: withdrawal_iface.TaskListResponse
	(*TaskItem)(nil),         // 5: withdrawal_iface.TaskItem
	(*SubmitWdRequest)(nil),  // 6: withdrawal_iface.SubmitWdRequest
	(*EmptyRequest)(nil),     // 7: withdrawal_iface.EmptyRequest
	(*CommonResponse)(nil),   // 8: withdrawal_iface.CommonResponse
}
var file_proto_withdrawal_service_withdrawal_proto_depIdxs = []int32{
	0,  // 0: withdrawal_iface.TaskListRequest.status:type_name -> withdrawal_iface.TaskStatus
	5,  // 1: withdrawal_iface.TaskListResponse.items:type_name -> withdrawal_iface.TaskItem
	1,  // 2: withdrawal_iface.TaskItem.source:type_name -> withdrawal_iface.ImporterSource
	2,  // 3: withdrawal_iface.TaskItem.mp_type:type_name -> withdrawal_iface.OrderMpType
	1,  // 4: withdrawal_iface.SubmitWdRequest.source:type_name -> withdrawal_iface.ImporterSource
	2,  // 5: withdrawal_iface.SubmitWdRequest.mp_type:type_name -> withdrawal_iface.OrderMpType
	6,  // 6: withdrawal_iface.WithdrawalService.SubmitWithdrawal:input_type -> withdrawal_iface.SubmitWdRequest
	3,  // 7: withdrawal_iface.WithdrawalService.GetTaskList:input_type -> withdrawal_iface.TaskListRequest
	7,  // 8: withdrawal_iface.WithdrawalService.Run:input_type -> withdrawal_iface.EmptyRequest
	7,  // 9: withdrawal_iface.WithdrawalService.Stop:input_type -> withdrawal_iface.EmptyRequest
	7,  // 10: withdrawal_iface.WithdrawalService.HealthCheck:input_type -> withdrawal_iface.EmptyRequest
	8,  // 11: withdrawal_iface.WithdrawalService.SubmitWithdrawal:output_type -> withdrawal_iface.CommonResponse
	4,  // 12: withdrawal_iface.WithdrawalService.GetTaskList:output_type -> withdrawal_iface.TaskListResponse
	8,  // 13: withdrawal_iface.WithdrawalService.Run:output_type -> withdrawal_iface.CommonResponse
	8,  // 14: withdrawal_iface.WithdrawalService.Stop:output_type -> withdrawal_iface.CommonResponse
	8,  // 15: withdrawal_iface.WithdrawalService.HealthCheck:output_type -> withdrawal_iface.CommonResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_withdrawal_service_withdrawal_proto_init() }
func file_proto_withdrawal_service_withdrawal_proto_init() {
	if File_proto_withdrawal_service_withdrawal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_withdrawal_service_withdrawal_proto_rawDesc), len(file_proto_withdrawal_service_withdrawal_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_withdrawal_service_withdrawal_proto_goTypes,
		DependencyIndexes: file_proto_withdrawal_service_withdrawal_proto_depIdxs,
		EnumInfos:         file_proto_withdrawal_service_withdrawal_proto_enumTypes,
		MessageInfos:      file_proto_withdrawal_service_withdrawal_proto_msgTypes,
	}.Build()
	File_proto_withdrawal_service_withdrawal_proto = out.File
	file_proto_withdrawal_service_withdrawal_proto_goTypes = nil
	file_proto_withdrawal_service_withdrawal_proto_depIdxs = nil
}
