/*
proto/withdrawal_service/withdrawal.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package http_sdk

import (
	"encoding/json"
)

// checks if the WithdrawalIfaceCommonResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WithdrawalIfaceCommonResponse{}

// WithdrawalIfaceCommonResponse struct for WithdrawalIfaceCommonResponse
type WithdrawalIfaceCommonResponse struct {
	Message *string `json:"message,omitempty"`
}

// NewWithdrawalIfaceCommonResponse instantiates a new WithdrawalIfaceCommonResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWithdrawalIfaceCommonResponse() *WithdrawalIfaceCommonResponse {
	this := WithdrawalIfaceCommonResponse{}
	return &this
}

// NewWithdrawalIfaceCommonResponseWithDefaults instantiates a new WithdrawalIfaceCommonResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWithdrawalIfaceCommonResponseWithDefaults() *WithdrawalIfaceCommonResponse {
	this := WithdrawalIfaceCommonResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *WithdrawalIfaceCommonResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithdrawalIfaceCommonResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *WithdrawalIfaceCommonResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *WithdrawalIfaceCommonResponse) SetMessage(v string) {
	o.Message = &v
}

func (o WithdrawalIfaceCommonResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WithdrawalIfaceCommonResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableWithdrawalIfaceCommonResponse struct {
	value *WithdrawalIfaceCommonResponse
	isSet bool
}

func (v NullableWithdrawalIfaceCommonResponse) Get() *WithdrawalIfaceCommonResponse {
	return v.value
}

func (v *NullableWithdrawalIfaceCommonResponse) Set(val *WithdrawalIfaceCommonResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWithdrawalIfaceCommonResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWithdrawalIfaceCommonResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWithdrawalIfaceCommonResponse(val *WithdrawalIfaceCommonResponse) *NullableWithdrawalIfaceCommonResponse {
	return &NullableWithdrawalIfaceCommonResponse{value: val, isSet: true}
}

func (v NullableWithdrawalIfaceCommonResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWithdrawalIfaceCommonResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


