/*
proto/withdrawal_service/withdrawal.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package http_sdk

import (
	"encoding/json"
)

// checks if the WithdrawalIfaceTaskListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WithdrawalIfaceTaskListResponse{}

// WithdrawalIfaceTaskListResponse struct for WithdrawalIfaceTaskListResponse
type WithdrawalIfaceTaskListResponse struct {
	Items []WithdrawalIfaceTaskItem `json:"items,omitempty"`
}

// NewWithdrawalIfaceTaskListResponse instantiates a new WithdrawalIfaceTaskListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWithdrawalIfaceTaskListResponse() *WithdrawalIfaceTaskListResponse {
	this := WithdrawalIfaceTaskListResponse{}
	return &this
}

// NewWithdrawalIfaceTaskListResponseWithDefaults instantiates a new WithdrawalIfaceTaskListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWithdrawalIfaceTaskListResponseWithDefaults() *WithdrawalIfaceTaskListResponse {
	this := WithdrawalIfaceTaskListResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *WithdrawalIfaceTaskListResponse) GetItems() []WithdrawalIfaceTaskItem {
	if o == nil || IsNil(o.Items) {
		var ret []WithdrawalIfaceTaskItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithdrawalIfaceTaskListResponse) GetItemsOk() ([]WithdrawalIfaceTaskItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *WithdrawalIfaceTaskListResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []WithdrawalIfaceTaskItem and assigns it to the Items field.
func (o *WithdrawalIfaceTaskListResponse) SetItems(v []WithdrawalIfaceTaskItem) {
	o.Items = v
}

func (o WithdrawalIfaceTaskListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WithdrawalIfaceTaskListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableWithdrawalIfaceTaskListResponse struct {
	value *WithdrawalIfaceTaskListResponse
	isSet bool
}

func (v NullableWithdrawalIfaceTaskListResponse) Get() *WithdrawalIfaceTaskListResponse {
	return v.value
}

func (v *NullableWithdrawalIfaceTaskListResponse) Set(val *WithdrawalIfaceTaskListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWithdrawalIfaceTaskListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWithdrawalIfaceTaskListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWithdrawalIfaceTaskListResponse(val *WithdrawalIfaceTaskListResponse) *NullableWithdrawalIfaceTaskListResponse {
	return &NullableWithdrawalIfaceTaskListResponse{value: val, isSet: true}
}

func (v NullableWithdrawalIfaceTaskListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWithdrawalIfaceTaskListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


