/*
proto/withdrawal_service/withdrawal.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package http_sdk

import (
	"encoding/json"
)

// checks if the WithdrawalIfaceTaskItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WithdrawalIfaceTaskItem{}

// WithdrawalIfaceTaskItem struct for WithdrawalIfaceTaskItem
type WithdrawalIfaceTaskItem struct {
	TeamId *string `json:"teamId,omitempty"`
	MpId *string `json:"mpId,omitempty"`
	Filename *string `json:"filename,omitempty"`
	Status *WithdrawalIfaceTaskStatus `json:"status,omitempty"`
	Source *WithdrawalIfaceImporterSource `json:"source,omitempty"`
	MpType *WithdrawalIfaceOrderMpType `json:"mpType,omitempty"`
	ResourceUri *string `json:"resourceUri,omitempty"`
	ErrMessage *string `json:"errMessage,omitempty"`
	IsErr *bool `json:"isErr,omitempty"`
}

// NewWithdrawalIfaceTaskItem instantiates a new WithdrawalIfaceTaskItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWithdrawalIfaceTaskItem() *WithdrawalIfaceTaskItem {
	this := WithdrawalIfaceTaskItem{}
	var status WithdrawalIfaceTaskStatus = TASK_UNKNOWN
	this.Status = &status
	var source WithdrawalIfaceImporterSource = SOURCE_UNKNOWN
	this.Source = &source
	var mpType WithdrawalIfaceOrderMpType = CUSTOM
	this.MpType = &mpType
	return &this
}

// NewWithdrawalIfaceTaskItemWithDefaults instantiates a new WithdrawalIfaceTaskItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWithdrawalIfaceTaskItemWithDefaults() *WithdrawalIfaceTaskItem {
	this := WithdrawalIfaceTaskItem{}
	var status WithdrawalIfaceTaskStatus = TASK_UNKNOWN
	this.Status = &status
	var source WithdrawalIfaceImporterSource = SOURCE_UNKNOWN
	this.Source = &source
	var mpType WithdrawalIfaceOrderMpType = CUSTOM
	this.MpType = &mpType
	return &this
}

// GetTeamId returns the TeamId field value if set, zero value otherwise.
func (o *WithdrawalIfaceTaskItem) GetTeamId() string {
	if o == nil || IsNil(o.TeamId) {
		var ret string
		return ret
	}
	return *o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithdrawalIfaceTaskItem) GetTeamIdOk() (*string, bool) {
	if o == nil || IsNil(o.TeamId) {
		return nil, false
	}
	return o.TeamId, true
}

// HasTeamId returns a boolean if a field has been set.
func (o *WithdrawalIfaceTaskItem) HasTeamId() bool {
	if o != nil && !IsNil(o.TeamId) {
		return true
	}

	return false
}

// SetTeamId gets a reference to the given string and assigns it to the TeamId field.
func (o *WithdrawalIfaceTaskItem) SetTeamId(v string) {
	o.TeamId = &v
}

// GetMpId returns the MpId field value if set, zero value otherwise.
func (o *WithdrawalIfaceTaskItem) GetMpId() string {
	if o == nil || IsNil(o.MpId) {
		var ret string
		return ret
	}
	return *o.MpId
}

// GetMpIdOk returns a tuple with the MpId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithdrawalIfaceTaskItem) GetMpIdOk() (*string, bool) {
	if o == nil || IsNil(o.MpId) {
		return nil, false
	}
	return o.MpId, true
}

// HasMpId returns a boolean if a field has been set.
func (o *WithdrawalIfaceTaskItem) HasMpId() bool {
	if o != nil && !IsNil(o.MpId) {
		return true
	}

	return false
}

// SetMpId gets a reference to the given string and assigns it to the MpId field.
func (o *WithdrawalIfaceTaskItem) SetMpId(v string) {
	o.MpId = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *WithdrawalIfaceTaskItem) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithdrawalIfaceTaskItem) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *WithdrawalIfaceTaskItem) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *WithdrawalIfaceTaskItem) SetFilename(v string) {
	o.Filename = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WithdrawalIfaceTaskItem) GetStatus() WithdrawalIfaceTaskStatus {
	if o == nil || IsNil(o.Status) {
		var ret WithdrawalIfaceTaskStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithdrawalIfaceTaskItem) GetStatusOk() (*WithdrawalIfaceTaskStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WithdrawalIfaceTaskItem) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given WithdrawalIfaceTaskStatus and assigns it to the Status field.
func (o *WithdrawalIfaceTaskItem) SetStatus(v WithdrawalIfaceTaskStatus) {
	o.Status = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *WithdrawalIfaceTaskItem) GetSource() WithdrawalIfaceImporterSource {
	if o == nil || IsNil(o.Source) {
		var ret WithdrawalIfaceImporterSource
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithdrawalIfaceTaskItem) GetSourceOk() (*WithdrawalIfaceImporterSource, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *WithdrawalIfaceTaskItem) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given WithdrawalIfaceImporterSource and assigns it to the Source field.
func (o *WithdrawalIfaceTaskItem) SetSource(v WithdrawalIfaceImporterSource) {
	o.Source = &v
}

// GetMpType returns the MpType field value if set, zero value otherwise.
func (o *WithdrawalIfaceTaskItem) GetMpType() WithdrawalIfaceOrderMpType {
	if o == nil || IsNil(o.MpType) {
		var ret WithdrawalIfaceOrderMpType
		return ret
	}
	return *o.MpType
}

// GetMpTypeOk returns a tuple with the MpType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithdrawalIfaceTaskItem) GetMpTypeOk() (*WithdrawalIfaceOrderMpType, bool) {
	if o == nil || IsNil(o.MpType) {
		return nil, false
	}
	return o.MpType, true
}

// HasMpType returns a boolean if a field has been set.
func (o *WithdrawalIfaceTaskItem) HasMpType() bool {
	if o != nil && !IsNil(o.MpType) {
		return true
	}

	return false
}

// SetMpType gets a reference to the given WithdrawalIfaceOrderMpType and assigns it to the MpType field.
func (o *WithdrawalIfaceTaskItem) SetMpType(v WithdrawalIfaceOrderMpType) {
	o.MpType = &v
}

// GetResourceUri returns the ResourceUri field value if set, zero value otherwise.
func (o *WithdrawalIfaceTaskItem) GetResourceUri() string {
	if o == nil || IsNil(o.ResourceUri) {
		var ret string
		return ret
	}
	return *o.ResourceUri
}

// GetResourceUriOk returns a tuple with the ResourceUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithdrawalIfaceTaskItem) GetResourceUriOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceUri) {
		return nil, false
	}
	return o.ResourceUri, true
}

// HasResourceUri returns a boolean if a field has been set.
func (o *WithdrawalIfaceTaskItem) HasResourceUri() bool {
	if o != nil && !IsNil(o.ResourceUri) {
		return true
	}

	return false
}

// SetResourceUri gets a reference to the given string and assigns it to the ResourceUri field.
func (o *WithdrawalIfaceTaskItem) SetResourceUri(v string) {
	o.ResourceUri = &v
}

// GetErrMessage returns the ErrMessage field value if set, zero value otherwise.
func (o *WithdrawalIfaceTaskItem) GetErrMessage() string {
	if o == nil || IsNil(o.ErrMessage) {
		var ret string
		return ret
	}
	return *o.ErrMessage
}

// GetErrMessageOk returns a tuple with the ErrMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithdrawalIfaceTaskItem) GetErrMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrMessage) {
		return nil, false
	}
	return o.ErrMessage, true
}

// HasErrMessage returns a boolean if a field has been set.
func (o *WithdrawalIfaceTaskItem) HasErrMessage() bool {
	if o != nil && !IsNil(o.ErrMessage) {
		return true
	}

	return false
}

// SetErrMessage gets a reference to the given string and assigns it to the ErrMessage field.
func (o *WithdrawalIfaceTaskItem) SetErrMessage(v string) {
	o.ErrMessage = &v
}

// GetIsErr returns the IsErr field value if set, zero value otherwise.
func (o *WithdrawalIfaceTaskItem) GetIsErr() bool {
	if o == nil || IsNil(o.IsErr) {
		var ret bool
		return ret
	}
	return *o.IsErr
}

// GetIsErrOk returns a tuple with the IsErr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithdrawalIfaceTaskItem) GetIsErrOk() (*bool, bool) {
	if o == nil || IsNil(o.IsErr) {
		return nil, false
	}
	return o.IsErr, true
}

// HasIsErr returns a boolean if a field has been set.
func (o *WithdrawalIfaceTaskItem) HasIsErr() bool {
	if o != nil && !IsNil(o.IsErr) {
		return true
	}

	return false
}

// SetIsErr gets a reference to the given bool and assigns it to the IsErr field.
func (o *WithdrawalIfaceTaskItem) SetIsErr(v bool) {
	o.IsErr = &v
}

func (o WithdrawalIfaceTaskItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WithdrawalIfaceTaskItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TeamId) {
		toSerialize["teamId"] = o.TeamId
	}
	if !IsNil(o.MpId) {
		toSerialize["mpId"] = o.MpId
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.MpType) {
		toSerialize["mpType"] = o.MpType
	}
	if !IsNil(o.ResourceUri) {
		toSerialize["resourceUri"] = o.ResourceUri
	}
	if !IsNil(o.ErrMessage) {
		toSerialize["errMessage"] = o.ErrMessage
	}
	if !IsNil(o.IsErr) {
		toSerialize["isErr"] = o.IsErr
	}
	return toSerialize, nil
}

type NullableWithdrawalIfaceTaskItem struct {
	value *WithdrawalIfaceTaskItem
	isSet bool
}

func (v NullableWithdrawalIfaceTaskItem) Get() *WithdrawalIfaceTaskItem {
	return v.value
}

func (v *NullableWithdrawalIfaceTaskItem) Set(val *WithdrawalIfaceTaskItem) {
	v.value = val
	v.isSet = true
}

func (v NullableWithdrawalIfaceTaskItem) IsSet() bool {
	return v.isSet
}

func (v *NullableWithdrawalIfaceTaskItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWithdrawalIfaceTaskItem(val *WithdrawalIfaceTaskItem) *NullableWithdrawalIfaceTaskItem {
	return &NullableWithdrawalIfaceTaskItem{value: val, isSet: true}
}

func (v NullableWithdrawalIfaceTaskItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWithdrawalIfaceTaskItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


