// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/stream_service/stream.proto

package stream_iface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RevalidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevalidateRequest) Reset() {
	*x = RevalidateRequest{}
	mi := &file_proto_stream_service_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevalidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevalidateRequest) ProtoMessage() {}

func (x *RevalidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_service_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevalidateRequest.ProtoReflect.Descriptor instead.
func (*RevalidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_service_stream_proto_rawDescGZIP(), []int{0}
}

func (x *RevalidateRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

type CommonReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonReq) Reset() {
	*x = CommonReq{}
	mi := &file_proto_stream_service_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonReq) ProtoMessage() {}

func (x *CommonReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_service_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonReq.ProtoReflect.Descriptor instead.
func (*CommonReq) Descriptor() ([]byte, []int) {
	return file_proto_stream_service_stream_proto_rawDescGZIP(), []int{1}
}

type CommonRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonRes) Reset() {
	*x = CommonRes{}
	mi := &file_proto_stream_service_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRes) ProtoMessage() {}

func (x *CommonRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_service_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRes.ProtoReflect.Descriptor instead.
func (*CommonRes) Descriptor() ([]byte, []int) {
	return file_proto_stream_service_stream_proto_rawDescGZIP(), []int{2}
}

func (x *CommonRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RevalidateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevalidateRes) Reset() {
	*x = RevalidateRes{}
	mi := &file_proto_stream_service_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevalidateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevalidateRes) ProtoMessage() {}

func (x *RevalidateRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_service_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevalidateRes.ProtoReflect.Descriptor instead.
func (*RevalidateRes) Descriptor() ([]byte, []int) {
	return file_proto_stream_service_stream_proto_rawDescGZIP(), []int{3}
}

func (x *RevalidateRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_stream_service_stream_proto protoreflect.FileDescriptor

const file_proto_stream_service_stream_proto_rawDesc = "" +
	"\n" +
	"!proto/stream_service/stream.proto\x12\fstream_iface\x1a\x1fgoogle/protobuf/timestamp.proto\"N\n" +
	"\x11RevalidateRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"\v\n" +
	"\tCommonReq\"%\n" +
	"\tCommonRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\")\n" +
	"\rRevalidateRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xd4\x01\n" +
	"\rStreamService\x12N\n" +
	"\x0eRevalidateFrom\x12\x1f.stream_iface.RevalidateRequest\x1a\x1b.stream_iface.RevalidateRes\x129\n" +
	"\x05Start\x12\x17.stream_iface.CommonReq\x1a\x17.stream_iface.CommonRes\x128\n" +
	"\x04Stop\x12\x17.stream_iface.CommonReq\x1a\x17.stream_iface.CommonResB\x1dZ\x1b./stream_iface;stream_ifaceb\x06proto3"

var (
	file_proto_stream_service_stream_proto_rawDescOnce sync.Once
	file_proto_stream_service_stream_proto_rawDescData []byte
)

func file_proto_stream_service_stream_proto_rawDescGZIP() []byte {
	file_proto_stream_service_stream_proto_rawDescOnce.Do(func() {
		file_proto_stream_service_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stream_service_stream_proto_rawDesc), len(file_proto_stream_service_stream_proto_rawDesc)))
	})
	return file_proto_stream_service_stream_proto_rawDescData
}

var file_proto_stream_service_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_stream_service_stream_proto_goTypes = []any{
	(*RevalidateRequest)(nil),     // 0: stream_iface.RevalidateRequest
	(*CommonReq)(nil),             // 1: stream_iface.CommonReq
	(*CommonRes)(nil),             // 2: stream_iface.CommonRes
	(*RevalidateRes)(nil),         // 3: stream_iface.RevalidateRes
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_stream_service_stream_proto_depIdxs = []int32{
	4, // 0: stream_iface.RevalidateRequest.start_time:type_name -> google.protobuf.Timestamp
	0, // 1: stream_iface.StreamService.RevalidateFrom:input_type -> stream_iface.RevalidateRequest
	1, // 2: stream_iface.StreamService.Start:input_type -> stream_iface.CommonReq
	1, // 3: stream_iface.StreamService.Stop:input_type -> stream_iface.CommonReq
	3, // 4: stream_iface.StreamService.RevalidateFrom:output_type -> stream_iface.RevalidateRes
	2, // 5: stream_iface.StreamService.Start:output_type -> stream_iface.CommonRes
	2, // 6: stream_iface.StreamService.Stop:output_type -> stream_iface.CommonRes
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_stream_service_stream_proto_init() }
func file_proto_stream_service_stream_proto_init() {
	if File_proto_stream_service_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stream_service_stream_proto_rawDesc), len(file_proto_stream_service_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stream_service_stream_proto_goTypes,
		DependencyIndexes: file_proto_stream_service_stream_proto_depIdxs,
		MessageInfos:      file_proto_stream_service_stream_proto_msgTypes,
	}.Build()
	File_proto_stream_service_stream_proto = out.File
	file_proto_stream_service_stream_proto_goTypes = nil
	file_proto_stream_service_stream_proto_depIdxs = nil
}
